---
title: "DiscussionWeek6 - Data 605"
author: "Stephanie Roark"
date: "3/6/2019"
output:
  html_document:
    highlight: pygments
    theme: cosmo
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```

## Chapter 3.2 Exercise 1

####Compute the following:

(a)${6 \choose 3}$ = `r choose(6,3)`

```{r a)}
choose(6,3)
```

${n \choose j}=(n)_j/j!=n!/j!(n-j)!$ = 6!/3!(6-3)!= `r factorial(6)/(factorial(3)*factorial(6-3))`

```{r a_2}
factorial(6)/(factorial(3)*factorial(6-3))
```

(b) $b(5, .2, 4)$ = 

$b(n, p, j) = {n \choose j}p^jq^n−j$ where $q = (1-p)$

= ${5 \choose 4}(1/5)^4*(4/5)^1$

```{r b}
choose(5,4)*(1/5)**4*(4/5)
```

(c)${7 \choose 2}$ = `r choose(7,3)`

(d)${26 \choose 26}$ = `r choose(26,26)`

(e) $b(4, .2, 3)$

```{r e}
choose(4,3)*(1/5)**3*(4/5)
```

(f)${6 \choose 2}$ = `r choose(6,2)`

(g)${10 \choose 9}$ = `r choose(10,9)`

(h) $b(8,.3,5)$

```{r h}
choose(8,5)*(.3)**5*(.7)**3
```


