---
title: "Data 607 Discussion Week 11"
author: "Stephanie Roark"
date: "11/7/2018"
output: html_document
---

https://github.com/StephRoark/cunymsds/blob/master/data607/607%20Discussion/Data607DiscussionWeek11.Rmd

Spotify Music for Everyone - Discover Weekly Recommender System

https://www.spotify.com/us/discoverweekly/


Every Monday morning Spotify will deliver a custom playlist of 30 new songs. These songs are specially curated based on your preferences and while it may take a little bit of time for spotify to get to know you and your preferences, they will soon be suggesting new songs that you would never have found on your own. Spotify's Discover weekly delivers new music suggestions based on a recommender system which finds similarities between the users and their song preferences in order to make match up or compare the users and make new song recommendations.

1. Perform a Scenario Design analysis as described below.  

Spotify Discover Weekly:

- Target Users - music listeners who want a curated list of new music each week 

- User's Key Goals - finding music that matches their listening preferences without having to search for it

- Accomplishing Goals - Spotify creates a list of music each week that is supposed to be similar or something that the user might like based on previous listening preferences


2. Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.

Spotify uses 3 different types of recommender models: Collaborative, NLP and Raw Audo Analyses. Collaborative recommendations creates associations between users and the songs they listen to or chose to save which can be compared to other users to create recommendations between the users. NLP is used to find web text about the music reviews , bands, lyrics, etc which can be used to determine relationships to music and make recommendations. And the raw audio files themselves can be used to make comparisons between songs to look for similarities. 


3. Include specific recommendations about how to improve the site's recommendation capabilities going forward. 

One idea for spotify's recommender system is to make recommendations that aren't exactly in line with the user but might be a surprise recommendation or something that the user might not have expected to like or want to hear.

